/**
 * Roh-Übersetzungen nach Sprachen getrennt.
 */
const rawTranslations: { [lang: string]: { [key: string]: string } } = {
	de: {
		'Active Users (3 month)': 'Nutzer (3 Monate)',
		'Active Users (6 month)': 'Nutzer (6 Monate)',
		'Active Users (Last Year)': 'Nutzer (Letztes Jahr)',
		'Num Disabled Users': 'Anzahl deaktivierter Benutzer',
		'App Updates available': 'App Updates verfügbar',
		'New Updates for apps': 'Neue Updates für Apps',
		'Available New Version': 'Neue NC-Version verfügbar',
		'Current Version': 'Installierte NC-Version',
		'CPU Load 1min': 'CPU Last 1min',
		'CPU Load 5min': 'CPU Last 5min',
		'CPU Load 15min': 'CPU Last 15min',
		'CPU Cores': 'CPU Kerne',
		'RAM Total': 'RAM Gesamt',
		'RAM Free': 'RAM Frei',
		'Swap Total': 'Swap Gesamt',
		'Free Disk Space': 'Festplatte Frei',
		'Memcache Local': 'Memcache Lokal',
		'Memcache Locking': 'Memcache Locking',
		'Installed Apps': 'Installierte Apps',
		'System Update available': 'System Update verfügbar',
		'Last Update Check': 'Letzter Update Check',
		'Total Users': 'Benutzer aktiv',
		'Total Files': 'Dateien gesamt',
		'Total Storages': 'Speichermedien',
		'Appdata Files': 'Appdata Dateien',
		'Total Shares': 'Freigaben gesamt',
		'Link Shares': 'Link Freigaben',
		'Talk Rooms': 'Talk Räume',
		'Federated Sent': 'Federated gesendet',
		'Webserver Type': 'Webserver Typ',
		'PHP Version': 'PHP Version',
		'PHP Memory Limit': 'PHP Speicher Limit',
		'Max Upload Size': 'Max Upload Größe',
		'Opcache Hit Rate': 'Opcache Trefferquote',
		'Opcache RAM used': 'Opcache RAM genutzt',
		'DB Type': 'DB Typ',
		'DB Version': 'DB Version',
		'DB Size': 'DB Größe',
		'FPM Active Processes': 'FPM Aktive Prozesse',
		'FPM Total Processes': 'FPM Prozesse gesamt',
		'FPM Idle Processes': 'FPM Idle Prozesse',
		'FPM Accepted Conn': 'FPM Akzeptierte Verb.',
		'FPM Max Active': 'FPM Max Aktive Prozesse',
		'APCu Entries': 'APCu Einträge',
		'APCu Cache Size': 'APCu Cache Größe',
		'APCu Hits': 'APCu Treffer',
		'Active Users (5 min)': 'Nutzer (5 Min)',
		'Active Users (1 h)': 'Nutzer (1 Std)',
		'Active Users (24 h)': 'Nutzer (24 Std)',
		'Active Users (1 month)': 'Nutzer (1 Monat)',
	},
	en: {
		'Active Users (3 month)': 'Active Users (3 month)',
		'Active Users (6 month)': 'Active Users (6 month)',
		'Active Users (Last Year)': 'Active Users (Last Year)',
		'Num Disabled Users': 'Num Disabled Users',
		'App Updates available': 'App Updates available',
		'New Updates for apps': 'New Updates for apps',
		'Available New Version': 'Available New Version',
		'Current Version': 'Current Version',
		'CPU Load 1min': 'CPU Load 1min',
		'CPU Load 5min': 'CPU Load 5min',
		'CPU Load 15min': 'CPU Load 15min',
		'CPU Cores': 'CPU Cores',
		'RAM Total': 'RAM Total',
		'RAM Free': 'RAM Free',
		'Swap Total': 'Swap Total',
		'Free Disk Space': 'Free Disk Space',
		'Memcache Local': 'Memcache Local',
		'Memcache Locking': 'Memcache Locking',
		'Installed Apps': 'Installed Apps',
		'System Update available': 'System Update available',
		'Last Update Check': 'Last Update Check',
		'Total Users': 'Total Users',
		'Total Files': 'Total Files',
		'Total Storages': 'Total Storages',
		'Appdata Files': 'Appdata Files',
		'Total Shares': 'Total Shares',
		'Link Shares': 'Link Shares',
		'Talk Rooms': 'Talk Rooms',
		'Federated Sent': 'Federated Sent',
		'Webserver Type': 'Webserver Type',
		'PHP Version': 'PHP Version',
		'PHP Memory Limit': 'PHP Memory Limit',
		'Max Upload Size': 'Max Upload Size',
		'Opcache Hit Rate': 'Opcache Hit Rate',
		'Opcache RAM used': 'Opcache RAM used',
		'DB Type': 'DB Type',
		'DB Version': 'DB Version',
		'DB Size': 'DB Size',
		'FPM Active Processes': 'FPM Active Processes',
		'FPM Total Processes': 'FPM Total Processes',
		'FPM Idle Processes': 'FPM Idle Processes',
		'FPM Accepted Conn': 'FPM Accepted Conn',
		'FPM Max Active': 'FPM Max Active',
		'APCu Entries': 'APCu Entries',
		'APCu Cache Size': 'APCu Cache Size',
		'APCu Hits': 'APCu Hits',
		'Active Users (5 min)': 'Active Users (5 min)',
		'Active Users (1 h)': 'Active Users (1 h)',
		'Active Users (24 h)': 'Active Users (24 h)',
		'Active Users (1 month)': 'Active Users (1 month)',
	},
	it: {
		'Active Users (3 month)': 'Utenti attivi (3 mesi)',
		'Active Users (6 month)': 'Utenti attivi (6 mesi)',
		'Active Users (Last Year)': 'Utenti attivi (Ultimo anno)',
		'Num Disabled Users': 'Utenti disabilitati',
		'App Updates available': 'Aggiornamenti app disponibili',
		'New Updates for apps': 'Nuovi aggiornamenti app',
		'Available New Version': 'Nuova versione disponibile',
		'Current Version': 'Versione installata',
		'CPU Load 1min': 'Carico CPU 1min',
		'CPU Load 5min': 'Carico CPU 5min',
		'CPU Load 15min': 'Carico CPU 15min',
		'CPU Cores': 'Core CPU',
		'RAM Total': 'RAM totale',
		'RAM Free': 'RAM libera',
		'Swap Total': 'Swap totale',
		'Free Disk Space': 'Spazio disco libero',
		'Memcache Local': 'Memcache locale',
		'Memcache Locking': 'Memcache locking',
		'Installed Apps': 'App installate',
		'System Update available': 'Aggiornamento sistema disponibile',
		'Last Update Check': 'Ultimo controllo',
		'Total Users': 'Utenti totali',
		'Total Files': 'File totali',
		'Total Storages': 'Storage totali',
		'Appdata Files': 'File Appdata',
		'Total Shares': 'Condivisioni totali',
		'Link Shares': 'Link condivisi',
		'Talk Rooms': 'Stanze Talk',
		'Federated Sent': 'Federated inviate',
		'Webserver Type': 'Tipo webserver',
		'PHP Version': 'Versione PHP',
		'PHP Memory Limit': 'Limite memoria PHP',
		'Max Upload Size': 'Dimensione max upload',
		'Opcache Hit Rate': 'Percentuale hit Opcache',
		'Opcache RAM used': 'RAM Opcache usato',
		'DB Type': 'Tipo DB',
		'DB Version': 'Versione DB',
		'DB Size': 'Dimensione DB',
		'FPM Active Processes': 'FPM processi attivi',
		'FPM Total Processes': 'FPM processi totali',
		'FPM Idle Processes': 'FPM processi inattivi',
		'FPM Accepted Conn': 'FPM connessioni accettate',
		'FPM Max Active': 'FPM max attivi',
		'APCu Entries': 'Voci APCu',
		'APCu Cache Size': 'Dimensione cache APCu',
		'APCu Hits': 'Hit APCu',
		'Active Users (5 min)': 'Utenti (5 min)',
		'Active Users (1 h)': 'Utenti (1 ora)',
		'Active Users (24 h)': 'Utenti (24 ore)',
		'Active Users (1 month)': 'Utenti (1 mese)',
	},
	fr: {
		'Active Users (3 month)': 'Utilisateurs (3 mois)',
		'Active Users (6 month)': 'Utilisateurs (6 mois)',
		'Active Users (Last Year)': 'Utilisateurs (An dernier)',
		'Num Disabled Users': 'Utilisateurs désactivés',
		'App Updates available': 'Mises à jour dispos',
		'New Updates for apps': 'Nouvelles mises à jour',
		'Available New Version': 'Nouvelle version disponible',
		'Current Version': 'Version installée',
		'CPU Load 1min': 'Charge CPU 1min',
		'CPU Load 5min': 'Charge CPU 5min',
		'CPU Load 15min': 'Charge CPU 15min',
		'CPU Cores': 'Cœurs CPU',
		'RAM Total': 'RAM totale',
		'RAM Free': 'RAM libre',
		'Swap Total': 'Swap total',
		'Free Disk Space': 'Espace disque libre',
		'Memcache Local': 'Memcache local',
		'Memcache Locking': 'Memcache locking',
		'Installed Apps': 'Apps installées',
		'System Update available': 'Mise à jour système disponible',
		'Last Update Check': 'Dernière vérification',
		'Total Users': 'Total utilisateurs',
		'Total Files': 'Total fichiers',
		'Total Storages': 'Total stockages',
		'Appdata Files': 'Fichiers Appdata',
		'Total Shares': 'Total partages',
		'Link Shares': 'Partages par lien',
		'Talk Rooms': 'Salons Talk',
		'Federated Sent': 'Federated envoyés',
		'Webserver Type': 'Type de serveur Web',
		'PHP Version': 'Version PHP',
		'PHP Memory Limit': 'Limite mémoire PHP',
		'Max Upload Size': 'Taille max upload',
		'Opcache Hit Rate': 'Taux de réussite Opcache',
		'Opcache RAM used': 'RAM Opcache utilisé',
		'DB Type': 'Type de base de données',
		'DB Version': 'Version de base de données',
		'DB Size': 'Taille de la base de données',
		'FPM Active Processes': 'FPM processus actifs',
		'FPM Total Processes': 'FPM processus totaux',
		'FPM Idle Processes': 'FPM processus inactifs',
		'FPM Accepted Conn': 'FPM connexions acceptées',
		'FPM Max Active': 'FPM max actifs',
		'APCu Entries': 'Entrées APCu',
		'APCu Cache Size': 'Taille cache APCu',
		'APCu Hits': 'Hits APCu',
		'Active Users (5 min)': 'Utilisateurs (5 min)',
		'Active Users (1 h)': 'Utilisateurs (1 h)',
		'Active Users (24 h)': 'Utilisateurs (24 h)',
		'Active Users (1 month)': 'Utilisateurs (1 mois)',
	},
	es: {
		'Active Users (3 month)': 'Usuarios (3 meses)',
		'Active Users (6 month)': 'Usuarios (6 meses)',
		'Active Users (Last Year)': 'Usuarios (Último año)',
		'Num Disabled Users': 'Usuarios deshabilitados',
		'App Updates available': 'Actualizaciones disponibles',
		'New Updates for apps': 'Nuevas actualizaciones',
		'Available New Version': 'Nueva versión disponible',
		'Current Version': 'Versión instalada',
		'CPU Load 1min': 'Carga CPU 1min',
		'CPU Load 5min': 'Carga CPU 5min',
		'CPU Load 15min': 'Carga CPU 15min',
		'CPU Cores': 'Núcleos CPU',
		'RAM Total': 'RAM total',
		'RAM Free': 'RAM libre',
		'Swap Total': 'Swap total',
		'Free Disk Space': 'Espacio libre',
		'Memcache Local': 'Memcache local',
		'Memcache Locking': 'Memcache locking',
		'Installed Apps': 'Apps instaladas',
		'System Update available': 'Actualización de sistema',
		'Last Update Check': 'Última comprobación',
		'Total Users': 'Usuarios totales',
		'Total Files': 'Archivos totales',
		'Total Storages': 'Almacenes totales',
		'Appdata Files': 'Archivos Appdata',
		'Total Shares': 'Total compartido',
		'Link Shares': 'Enlaces compartidos',
		'Talk Rooms': 'Salas Talk',
		'Federated Sent': 'Federated enviados',
		'Webserver Type': 'Tipo servidor web',
		'PHP Version': 'Versión PHP',
		'PHP Memory Limit': 'Límite memoria PHP',
		'Max Upload Size': 'Tamaño máx. subida',
		'Opcache Hit Rate': 'Tasa aciertos Opcache',
		'Opcache RAM used': 'RAM Opcache usada',
		'DB Type': 'Tipo BD',
		'DB Version': 'Versión BD',
		'DB Size': 'Tamaño BD',
		'FPM Active Processes': 'FPM procesos activos',
		'FPM Total Processes': 'FPM procesos totales',
		'FPM Idle Processes': 'FPM procesos inactivos',
		'FPM Accepted Conn': 'FPM conexiones aceptadas',
		'FPM Max Active': 'FPM máx. activos',
		'APCu Entries': 'Entradas APCu',
		'APCu Cache Size': 'Tamaño caché APCu',
		'APCu Hits': 'Hits APCu',
		'Active Users (5 min)': 'Usuarios (5 min)',
		'Active Users (1 h)': 'Usuarios (1 h)',
		'Active Users (24 h)': 'Usuarios (24 h)',
		'Active Users (1 month)': 'Usuarios (1 mes)',
	},
	nl: {
		'Active Users (3 month)': 'Gebruikers (3 mnd)',
		'Active Users (6 month)': 'Gebruikers (6 mnd)',
		'Active Users (Last Year)': 'Gebruikers (Vorig jaar)',
		'Num Disabled Users': 'Uitgeschakelde gebruikers',
		'App Updates available': 'App-updates beschikbaar',
		'New Updates for apps': 'Nieuwe app-updates',
		'Available New Version': 'Nieuwe versie beschikbaar',
		'Current Version': 'Huidige versie',
		'CPU Load 1min': 'CPU belasting 1min',
		'CPU Load 5min': 'CPU belasting 5min',
		'CPU Load 15min': 'CPU belasting 15min',
		'CPU Cores': 'CPU kernen',
		'RAM Total': 'RAM totaal',
		'RAM Free': 'RAM vrij',
		'Swap Total': 'Swap totaal',
		'Free Disk Space': 'Vrije schijfruimte',
		'Memcache Local': 'Memcache lokaal',
		'Memcache Locking': 'Memcache locking',
		'Installed Apps': 'Geïnstalleerde apps',
		'System Update available': 'Systeemupdate beschikbaar',
		'Last Update Check': 'Laatste controle',
		'Total Users': 'Totaal gebruikers',
		'Total Files': 'Totaal bestanden',
		'Total Storages': 'Totaal opslag',
		'Appdata Files': 'Appdata bestanden',
		'Total Shares': 'Totaal gedeeld',
		'Link Shares': 'Gedeelde links',
		'Talk Rooms': 'Talk kamers',
		'Federated Sent': 'Federated verzonden',
		'Webserver Type': 'Type webserver',
		'PHP Version': 'PHP versie',
		'PHP Memory Limit': 'PHP geheugenlimiet',
		'Max Upload Size': 'Max uploadgrootte',
		'Opcache Hit Rate': 'Opcache hitpercentage',
		'Opcache RAM used': 'Opcache RAM gebruikt',
		'DB Type': 'DB type',
		'DB Version': 'DB versie',
		'DB Size': 'DB grootte',
		'FPM Active Processes': 'FPM actieve processen',
		'FPM Total Processes': 'FPM totale processen',
		'FPM Idle Processes': 'FPM inactieve processen',
		'FPM Accepted Conn': 'FPM geaccepteerde verbindingen',
		'FPM Max Active': 'FPM max actieve processen',
		'APCu Entries': 'APCu items',
		'APCu Cache Size': 'APCu cache grootte',
		'APCu Hits': 'APCu hits',
		'Active Users (5 min)': 'Gebruikers (5 min)',
		'Active Users (1 h)': 'Gebruikers (1 uur)',
		'Active Users (24 h)': 'Gebruikers (24 uur)',
		'Active Users (1 month)': 'Gebruikers (1 maand)',
	},
	ru: {
		'Active Users (3 month)': 'Пользователи (3 мес)',
		'Active Users (6 month)': 'Пользователи (6 мес)',
		'Active Users (Last Year)': 'Пользователи (За год)',
		'Num Disabled Users': 'Отключенные пользователи',
		'App Updates available': 'Доступны обновления приложений',
		'New Updates for apps': 'Новые обновления приложений',
		'Available New Version': 'Доступна новая версия',
		'Current Version': 'Установленная версия',
		'CPU Load 1min': 'Загрузка ЦП 1 мин',
		'CPU Load 5min': 'Загрузка ЦП 5 мин',
		'CPU Load 15min': 'Загрузка ЦП 15 мин',
		'CPU Cores': 'Ядра ЦП',
		'RAM Total': 'Всего ОЗУ',
		'RAM Free': 'Свободно ОЗУ',
		'Swap Total': 'Всего Swap',
		'Free Disk Space': 'Свободное место',
		'Memcache Local': 'Локальный Memcache',
		'Memcache Locking': 'Memcache блокировка',
		'Installed Apps': 'Установленные приложения',
		'System Update available': 'Обновление системы',
		'Last Update Check': 'Последняя проверка',
		'Total Users': 'Всего пользователей',
		'Total Files': 'Всего файлов',
		'Total Storages': 'Всего хранилищ',
		'Appdata Files': 'Файлы Appdata',
		'Total Shares': 'Всего ресурсов',
		'Link Shares': 'Общие ссылки',
		'Talk Rooms': 'Комнаты Talk',
		'Federated Sent': 'Federated отправлено',
		'Webserver Type': 'Тип веб-сервера',
		'PHP Version': 'Версия PHP',
		'PHP Memory Limit': 'Лимит памяти PHP',
		'Max Upload Size': 'Макс. загрузка',
		'Opcache Hit Rate': 'Попадания Opcache',
		'Opcache RAM used': 'ОЗУ Opcache',
		'DB Type': 'Тип БД',
		'DB Version': 'Версия БД',
		'DB Size': 'Размер БД',
		'FPM Active Processes': 'Активные FPM',
		'FPM Total Processes': 'Всего FPM',
		'FPM Idle Processes': 'Ожидающие FPM',
		'FPM Accepted Conn': 'Принятые соед. FPM',
		'FPM Max Active': 'Макс. активных FPM',
		'APCu Entries': 'Записи APCu',
		'APCu Cache Size': 'Размер кэша APCu',
		'APCu Hits': 'Попадания APCu',
		'Active Users (5 min)': 'Пользователи (5 мин)',
		'Active Users (1 h)': 'Пользователи (1 ч)',
		'Active Users (24 h)': 'Пользователи (24 ч)',
		'Active Users (1 month)': 'Пользователи (1 мес)',
	},
	uk: {
		'Active Users (3 month)': 'Користувачі (3 міс)',
		'Active Users (6 month)': 'Користувачі (6 міс)',
		'Active Users (Last Year)': 'Користувачі (Рік)',
		'Num Disabled Users': 'Відключені користувачі',
		'App Updates available': 'Доступні оновлення додатків',
		'New Updates for apps': 'Нові оновлення додатків',
		'Available New Version': 'Доступна нова версія',
		'Current Version': 'Версія NC',
		'CPU Load 1min': 'Навантаження ЦП 1 хв',
		'CPU Load 5min': 'Навантаження ЦП 5 хв',
		'CPU Load 15min': 'Навантаження ЦП 15 хв',
		'CPU Cores': 'Ядра ЦП',
		'RAM Total': 'Всього ОЗП',
		'RAM Free': 'Свободно ОЗП',
		'Swap Total': 'Всього Swap',
		'Free Disk Space': 'Вільно на диску',
		'Memcache Local': 'Локальний Memcache',
		'Memcache Locking': 'Memcache блокування',
		'Installed Apps': 'Встановлені додатки',
		'System Update available': 'Оновлення системи',
		'Last Update Check': 'Остання перевірка',
		'Total Users': 'Всього користувачів',
		'Total Files': 'Всього файлів',
		'Total Storages': 'Всього сховищ',
		'Appdata Files': 'Файли Appdata',
		'Total Shares': 'Всього поширень',
		'Link Shares': 'Поширення за посиланням',
		'Talk Rooms': 'Кімнати Talk',
		'Federated Sent': 'Federated надіслано',
		'Webserver Type': 'Тип веб-сервера',
		'PHP Version': 'Версія PHP',
		'PHP Memory Limit': 'Ліміт пам’яті PHP',
		'Max Upload Size': 'Макс. завантаження',
		'Opcache Hit Rate': 'Попадання Opcache',
		'Opcache RAM used': 'ОЗП Opcache',
		'DB Type': 'Тип БД',
		'DB Version': 'Версія БД',
		'DB Size': 'Розмір БД',
		'FPM Active Processes': 'Активні FPM',
		'FPM Total Processes': 'Всього FPM',
		'FPM Idle Processes': 'Вільні FPM',
		'FPM Accepted Conn': 'Прийняті соед. FPM',
		'FPM Max Active': 'Макс. активних FPM',
		'APCu Entries': 'Записи APCu',
		'APCu Cache Size': 'Розмір кэша APCu',
		'APCu Hits': 'Попадання APCu',
		'Active Users (5 min)': 'Користувачі (5 хв)',
		'Active Users (1 h)': 'Користувачі (1 год)',
		'Active Users (24 h)': 'Користувачі (24 год)',
		'Active Users (1 month)': 'Користувачі (1 міс)',
	},
	zh: {
		'Active Users (3 month)': '活跃用户 (3个月)',
		'Active Users (6 month)': '活跃用户 (6个月)',
		'Active Users (Last Year)': '活跃用户 (去年)',
		'Num Disabled Users': '禁用用户数',
		'App Updates available': '应用更新可用',
		'New Updates for apps': '新的应用更新',
		'Available New Version': '有新版本可用',
		'Current Version': '当前版本',
		'CPU Load 1min': 'CPU负载 1分钟',
		'CPU Load 5min': 'CPU负载 5分钟',
		'CPU Load 15min': 'CPU负载 15分钟',
		'CPU Cores': 'CPU核心数',
		'RAM Total': '总内存',
		'RAM Free': '空闲内存',
		'Swap Total': '总交换分区',
		'Free Disk Space': '可用磁盘空间',
		'Memcache Local': '本地缓存',
		'Memcache Locking': '锁定缓存',
		'Installed Apps': '已安装应用',
		'System Update available': '系统更新可用',
		'Last Update Check': '最近检查时间',
		'Total Users': '总用户数',
		'Total Files': '总文件数',
		'Total Storages': '总存储数',
		'Appdata Files': 'Appdata文件',
		'Total Shares': '总共享数',
		'Link Shares': '链接共享',
		'Talk Rooms': 'Talk房间',
		'Federated Sent': '联合发送',
		'Webserver Type': 'Web服务器类型',
		'PHP Version': 'PHP版本',
		'PHP Memory Limit': 'PHP内存限制',
		'Max Upload Size': '最大上传限制',
		'Opcache Hit Rate': 'Opcache命中率',
		'Opcache RAM used': 'Opcache内存使用',
		'DB Type': '数据库类型',
		'DB Version': '数据库版本',
		'DB Size': '数据库大小',
		'FPM Active Processes': 'FPM活动进程',
		'FPM Total Processes': 'FPM总进程',
		'FPM Idle Processes': 'FPM空闲进程',
		'FPM Accepted Conn': 'FPM接受连接',
		'FPM Max Active': 'FPM最大活动进程',
		'APCu Entries': 'APCu条目',
		'APCu Cache Size': 'APCu缓存大小',
		'APCu Hits': 'APCu命中',
		'Active Users (5 min)': '活跃用户 (5分钟)',
		'Active Users (1 h)': '活跃用户 (1小时)',
		'Active Users (24 h)': '活跃用户 (24小时)',
		'Active Users (1 month)': '活跃用户 (1月)',
	},
	pl: {
		'Active Users (3 month)': 'Użytkownicy (3 mies)',
		'Active Users (6 month)': 'Użytkownicy (6 mies)',
		'Active Users (Last Year)': 'Użytkownicy (Rok)',
		'Num Disabled Users': 'Wyłączeni użytkownicy',
		'App Updates available': 'Dostępne aktualizacje aplikacji',
		'New Updates for apps': 'Nowe aktualizacje aplikacji',
		'Available New Version': 'Dostępna nowa wersja',
		'Current Version': 'Zainstalowana wersja',
		'CPU Load 1min': 'Obciążenie CPU 1min',
		'CPU Load 5min': 'Obciążenie CPU 5min',
		'CPU Load 15min': 'Obciążenie CPU 15min',
		'CPU Cores': 'Rdzenie CPU',
		'RAM Total': 'RAM całkowity',
		'RAM Free': 'RAM wolny',
		'Swap Total': 'Swap całkowity',
		'Free Disk Space': 'Wolne miejsce na dysku',
		'Memcache Local': 'Lokalny Memcache',
		'Memcache Locking': 'Memcache locking',
		'Installed Apps': 'Zainstalowane aplikacje',
		'System Update available': 'Aktualizacja systemu',
		'Last Update Check': 'Ostatnie sprawdzenie',
		'Total Users': 'Suma użytkowników',
		'Total Files': 'Suma plików',
		'Total Storages': 'Suma magazynów',
		'Appdata Files': 'Pliki Appdata',
		'Total Shares': 'Suma udostępnień',
		'Link Shares': 'Udostępnione linki',
		'Talk Rooms': 'Pokoje Talk',
		'Federated Sent': 'Federated wysłane',
		'Webserver Type': 'Typ serwera WWW',
		'PHP Version': 'Wersja PHP',
		'PHP Memory Limit': 'Limit pamięci PHP',
		'Max Upload Size': 'Maks. wielkość uploadu',
		'Opcache Hit Rate': 'Współczynnik hitów Opcache',
		'Opcache RAM used': 'Użyty RAM Opcache',
		'DB Type': 'Typ bazy danych',
		'DB Version': 'Wersja bazy danych',
		'DB Size': 'Rozmiar bazy danych',
		'FPM Active Processes': 'Aktywne procesy FPM',
		'FPM Total Processes': 'Suma procesów FPM',
		'FPM Idle Processes': 'Bezczynne procesy FPM',
		'FPM Accepted Conn': 'Zaakceptowane połączenia FPM',
		'FPM Max Active': 'Maks. aktywne FPM',
		'APCu Entries': 'Wpisy APCu',
		'APCu Cache Size': 'Rozmiar cache APCu',
		'APCu Hits': 'Hity APCu',
		'Active Users (5 min)': 'Użytkownicy (5 min)',
		'Active Users (1 h)': 'Użytkownicy (1 godz)',
		'Active Users (24 h)': 'Użytkownicy (24 godz)',
		'Active Users (1 month)': 'Użytkownicy (1 mies)',
	},
	pt: {
		'Active Users (3 month)': 'Usuários (3 meses)',
		'Active Users (6 month)': 'Usuários (6 meses)',
		'Active Users (Last Year)': 'Usuários (Ano passado)',
		'Num Disabled Users': 'Usuários desativados',
		'App Updates available': 'Atualizações disponíveis',
		'New Updates for apps': 'Novas atualizações',
		'Available New Version': 'Nova versão disponível',
		'Current Version': 'Versão instalada',
		'CPU Load 1min': 'Carga CPU 1min',
		'CPU Load 5min': 'Carga CPU 5min',
		'CPU Load 15min': 'Carga CPU 15min',
		'CPU Cores': 'Núcleos CPU',
		'RAM Total': 'RAM total',
		'RAM Free': 'RAM livre',
		'Swap Total': 'Swap total',
		'Free Disk Space': 'Espaço livre em disco',
		'Memcache Local': 'Memcache local',
		'Memcache Locking': 'Memcache locking',
		'Installed Apps': 'Apps instalados',
		'System Update available': 'Atualização de sistema',
		'Last Update Check': 'Última verificação',
		'Total Users': 'Total de usuários',
		'Total Files': 'Total de arquivos',
		'Total Storages': 'Total de armazenamentos',
		'Appdata Files': 'Arquivos Appdata',
		'Total Shares': 'Total partilhado',
		'Link Shares': 'Links partilhados',
		'Talk Rooms': 'Salas de Talk',
		'Federated Sent': 'Federated enviados',
		'Webserver Type': 'Tipo servidor web',
		'PHP Version': 'Versão PHP',
		'PHP Memory Limit': 'Limite memória PHP',
		'Max Upload Size': 'Tamanho máx. upload',
		'Opcache Hit Rate': 'Taxa de acerto Opcache',
		'Opcache RAM used': 'RAM Opcache usada',
		'DB Type': 'Tipo BD',
		'DB Version': 'Versão BD',
		'DB Size': 'Tamanho BD',
		'FPM Active Processes': 'FPM processos ativos',
		'FPM Total Processes': 'FPM processos totais',
		'FPM Idle Processes': 'FPM processos inativos',
		'FPM Accepted Conn': 'FPM conexões aceites',
		'FPM Max Active': 'FPM máx. ativos',
		'APCu Entries': 'Entradas APCu',
		'APCu Cache Size': 'Tamanho cache APCu',
		'APCu Hits': 'Hits APCu',
		'Active Users (5 min)': 'Usuários (5 min)',
		'Active Users (1 h)': 'Usuários (1 hora)',
		'Active Users (24 h)': 'Usuários (24 horas)',
		'Active Users (1 month)': 'Usuários (1 mês)',
	},
};

/**
 * Wandelt die strukturierte Liste in das von ioBroker benötigte Format um.
 */
function getTranslations(): { [key: string]: ioBroker.StringOrTranslated } {
	const result: { [key: string]: any } = {};
	for (const lang in rawTranslations) {
		for (const key in rawTranslations[lang]) {
			if (!result[key]) {
				result[key] = {};
			}
			result[key][lang] = rawTranslations[lang][key];
		}
	}
	return result;
}

export const words = getTranslations();
