/**
 * Roh-Übersetzungen nach Sprachen getrennt.
 */
const rawTranslations: { [lang: string]: { [key: string]: string } } = {
	de: {
		Version: 'Version',
		'CPU Load 1min': 'CPU Last 1min',
		'CPU Load 5min': 'CPU Last 5min',
		'CPU Load 15min': 'CPU Last 15min',
		'CPU Cores': 'CPU Kerne',
		'RAM Total': 'RAM Gesamt',
		'RAM Free': 'RAM Frei',
		'Swap Total': 'Swap Gesamt',
		'Free Disk Space': 'Festplatte Frei',
		'Memcache Local': 'Memcache Lokal',
		'Memcache Locking': 'Memcache Locking',
		'Installed Apps': 'Installierte Apps',
		'Updates available': 'Updates verfügbar',
		'System Update available': 'System Update verfügbar',
		'Last Update Check': 'Letzter Update Check',
		'Total Users': 'Benutzer aktiv',
		'Total Files': 'Dateien gesamt',
		'Total Storages': 'Speichermedien',
		'Appdata Files': 'Appdata Dateien',
		'Total Shares': 'Freigaben gesamt',
		'Link Shares': 'Link Freigaben',
		'Talk Rooms': 'Talk Räume',
		'Federated Sent': 'Federated gesendet',
		'Webserver Type': 'Webserver Typ',
		'PHP Version': 'PHP Version',
		'PHP Memory Limit': 'PHP Speicher Limit',
		'Max Upload Size': 'Max Upload Größe',
		'Opcache Hit Rate': 'Opcache Hit Rate',
		'Opcache RAM used': 'Opcache RAM genutzt',
		'DB Type': 'DB Typ',
		'DB Version': 'DB Version',
		'DB Size': 'DB Größe',
		'FPM Active Processes': 'FPM Aktive Prozesse',
		'FPM Total Processes': 'FPM Prozesse gesamt',
		'FPM Idle Processes': 'FPM Idle Prozesse',
		'FPM Accepted Conn': 'FPM Akzeptierte Verb.',
		'FPM Max Active': 'FPM Max Aktive Prozesse',
		'APCu Entries': 'APCu Einträge',
		'APCu Cache Size': 'APCu Cache Größe',
		'APCu Hits': 'APCu Hits',
		'Active Users (5 min)': 'Nutzer (5 Min)',
		'Active Users (1 h)': 'Nutzer (1 Std)',
		'Active Users (24 h)': 'Nutzer (24 Std)',
		'Active Users (1 month)': 'Nutzer (1 Monat)',
	},
	en: {
		Version: 'Version',
		'CPU Load 1min': 'CPU Load 1min',
		'CPU Load 5min': 'CPU Load 5min',
		'CPU Load 15min': 'CPU Load 15min',
		'CPU Cores': 'CPU Cores',
		'RAM Total': 'RAM Total',
		'RAM Free': 'RAM Free',
		'Swap Total': 'Swap Total',
		'Free Disk Space': 'Free Disk Space',
		'Memcache Local': 'Memcache Local',
		'Memcache Locking': 'Memcache Locking',
		'Installed Apps': 'Installed Apps',
		'Updates available': 'Updates available',
		'System Update available': 'System Update available',
		'Last Update Check': 'Last Update Check',
		'Total Users': 'Total Users',
		'Total Files': 'Total Files',
		'Total Storages': 'Total Storages',
		'Appdata Files': 'Appdata Files',
		'Total Shares': 'Total Shares',
		'Link Shares': 'Link Shares',
		'Talk Rooms': 'Talk Rooms',
		'Federated Sent': 'Federated Sent',
		'Webserver Type': 'Webserver Type',
		'PHP Version': 'PHP Version',
		'PHP Memory Limit': 'PHP Memory Limit',
		'Max Upload Size': 'Max Upload Size',
		'Opcache Hit Rate': 'Opcache Hit Rate',
		'Opcache RAM used': 'Opcache RAM used',
		'DB Type': 'DB Type',
		'DB Version': 'DB Version',
		'DB Size': 'DB Size',
		'FPM Active Processes': 'FPM Active Processes',
		'FPM Total Processes': 'FPM Total Processes',
		'FPM Idle Processes': 'FPM Idle Processes',
		'FPM Accepted Conn': 'FPM Accepted Conn',
		'FPM Max Active': 'FPM Max Active',
		'APCu Entries': 'APCu Entries',
		'APCu Cache Size': 'APCu Cache Size',
		'APCu Hits': 'APCu Hits',
		'Active Users (5 min)': 'Active Users (5 min)',
		'Active Users (1 h)': 'Active Users (1 h)',
		'Active Users (24 h)': 'Active Users (24 h)',
		'Active Users (1 month)': 'Active Users (1 month)',
	},
	it: {
		Version: 'Versione',
		'CPU Load 1min': 'Carico CPU 1min',
		'CPU Load 5min': 'Carico CPU 5min',
		'CPU Load 15min': 'Carico CPU 15min',
		'CPU Cores': 'Core CPU',
		'RAM Total': 'RAM Totale',
		'RAM Free': 'RAM Libero',
		'Swap Total': 'Swap Totale',
		'Free Disk Space': 'Spazio Libero',
		'Memcache Local': 'Memcache Locale',
		'Memcache Locking': 'Memcache Locking',
		'Installed Apps': 'App Installate',
		'Updates available': 'Aggiornamenti disponibili',
		'System Update available': 'Aggiornamento Sistema disponibile',
		'Last Update Check': 'Ultimo Controllo Aggiornamenti',
		'Total Users': 'Utenti Totali',
		'Total Files': 'File Totali',
		'Total Storages': 'Storaggi Totali',
		'Appdata Files': 'File Appdata',
		'Total Shares': 'Condivisioni Totali',
		'Link Shares': 'Condivisioni Link',
		'Talk Rooms': 'Stanza Talk',
		'Federated Sent': 'Federated Inviate',
		'Webserver Type': 'Tipo Webserver',
		'PHP Version': 'Versione PHP',
		'PHP Memory Limit': 'Limite Memoria PHP',
		'Max Upload Size': 'Dimensione Massima Upload',
		'Opcache Hit Rate': 'Rate Opcache',
		'Opcache RAM used': 'RAM Opcache Utilizzato',
		'DB Type': 'Tipo DB',
		'DB Version': 'Versione DB',
		'DB Size': 'Dimensione DB',
		'FPM Active Processes': 'Processi Attivi FPM',
		'FPM Total Processes': 'Processi Totali FPM',
		'FPM Idle Processes': 'Processi Inattivi FPM',
		'FPM Accepted Conn': 'Connessioni Accettate FPM',
		'FPM Max Active': 'Max Attivi FPM',
		'APCu Entries': 'Elementi APCu',
		'APCu Cache Size': 'Dimensione Cache APCu',
		'APCu Hits': 'Hit APCu',
		'Active Users (5 min)': 'Utenti Attivi (5 min)',
		'Active Users (1 h)': 'Utenti Attivi (1 h)',
		'Active Users (24 h)': 'Utenti Attivi (24 h)',
		'Active Users (1 month)': 'Utenti Attivi (1 month)',
	},
	fr: {
		Version: 'Version',
		'CPU Load 1min': 'Charge CPU 1min',
		'CPU Load 5min': 'Charge CPU 5min',
		'CPU Load 15min': 'Charge CPU 15min',
		'CPU Cores': 'Cores CPU',
		'RAM Total': 'RAM Total',
		'RAM Free': 'RAM Libre',
		'Swap Total': 'Swap Total',
		'Free Disk Space': 'Espace Libre',
		'Memcache Local': 'Memcache Local',
		'Memcache Locking': 'Memcache Locking',
		'Installed Apps': 'Applications Installées',
		'Updates available': 'Mises à jour disponibles',
		'System Update available': 'Mises à jour du système disponible',
		'Last Update Check': 'Dernière verification de mise à jour',
		'Total Users': 'Utilisateurs totaux',
		'Total Files': 'Fichiers totaux',
		'Total Storages': 'Stockages totaux',
		'Appdata Files': 'Fichiers Appdata',
		'Total Shares': 'Partages totaux',
		'Link Shares': 'Partages de liens',
		'Talk Rooms': 'Salons Talk',
		'Federated Sent': 'Federated envoyé',
		'Webserver Type': 'Type de serveur Web',
		'PHP Version': 'Version PHP',
		'PHP Memory Limit': 'Limite de lamoire PHP',
		'Max Upload Size': 'Taille maximale de transfert',
		'Opcache Hit Rate': 'Taux de hits Opcache',
		'Opcache RAM used': 'RAM Opcache utilisé',
		'DB Type': 'Type de base de données',
		'DB Version': 'Version de la base de données',
		'DB Size': 'Taille de la base de données',
		'FPM Active Processes': 'Processus actifs FPM',
		'FPM Total Processes': 'Processus totaux FPM',
		'FPM Idle Processes': 'Processus inactifs FPM',
		'FPM Accepted Conn': 'Connexions acceptées FPM',
		'FPM Max Active': 'Actifs FPM Max',
		'APCu Entries': 'Entrées APCu',
		'APCu Cache Size': 'Taille de la cache APCu',
		'APCu Hits': 'Hits APCu',
		'Active Users (5 min)': 'Utilisateurs actifs (5 min)',
		'Active Users (1 h)': 'Utilisateurs actifs (1 h)',
		'Active Users (24 h)': 'Utilisateurs actifs (24 h)',
		'Active Users (1 month)': 'Utilisateurs actifs (1 mois)',
	},
	es: {
		Version: 'Versión',
		'CPU Load 1min': 'Carga CPU 1min',
		'CPU Load 5min': 'Carga CPU 5min',
		'CPU Load 15min': 'Carga CPU 15min',
		'CPU Cores': 'Cores CPU',
		'RAM Total': 'RAM Total',
		'RAM Free': 'RAM Libre',
		'Swap Total': 'Swap Total',
		'Free Disk Space': 'Espacio Libre',
		'Memcache Local': 'Memcache Local',
		'Memcache Locking': 'Memcache Locking',
		'Installed Apps': 'Aplicaciones Instaladas',
		'Updates available': 'Actualizaciones disponibles',
		'System Update available': 'Actualización del sistema disponible',
		'Last Update Check': 'Verificación de actualización',
		'Total Users': 'Usuarios totales',
		'Total Files': 'Archivos totales',
		'Total Storages': 'Almacenes totales',
		'Appdata Files': 'Archivos Appdata',
		'Total Shares': 'Compartimentos totales',
		'Link Shares': 'Compartimentos de enlaces',
		'Talk Rooms': 'Salones Talk',
		'Federated Sent': 'Federated enviado',
		'Webserver Type': 'Tipo de servidor Web',
		'PHP Version': 'Versión PHP',
		'PHP Memory Limit': 'Limite de la memoria PHP',
		'Max Upload Size': 'Tamaño máximo de carga',
		'Opcache Hit Rate': 'Tasa de hits Opcache',
		'Opcache RAM used': 'RAM Opcache utilizada',
		'DB Type': 'Tipo de base de datos',
		'DB Version': 'Versión de la base de datos',
		'DB Size': 'Tamaño de la base de datos',
		'FPM Active Processes': 'Procesos activos FPM',
		'FPM Total Processes': 'Procesos totales FPM',
		'FPM Idle Processes': 'Procesos inactivos FPM',
		'FPM Accepted Conn': 'Conexiones aceptadas FPM',
		'FPM Max Active': 'Activos FPM Max',
		'APCu Entries': 'Entradas APCu',
		'APCu Cache Size': 'Tamaño de la cache APCu',
		'APCu Hits': 'Hits APCu',
		'Active Users (5 min)': 'Usuarios activos (5 min)',
		'Active Users (1 h)': 'Usuarios activos (1 h)',
		'Active Users (24 h)': 'Usuarios activos (24 h)',
		'Active Users (1 month)': 'Usuarios activos (1 mes)',
	},
	nl: {
		'CPU Load 1min': 'CPU laden 1min',
		'CPU Load 5min': 'CPU laden 5min',
		'CPU Load 15min': 'CPU laden 15min',
		'CPU Cores': 'CPU cores',
		'RAM Total': 'RAM totaal',
		'RAM Free': 'RAM vrij',
		'Swap Total': 'Swap totaal',
		'Free Disk Space': 'Vrij diskruimte',
		'Memcache Local': 'Memcache lokale',
		'Memcache Locking': 'Memcache locking',
		'Installed Apps': 'Geinstalleerde apps',
		'Updates available': 'Updates beschikbaar',
		'System Update available': 'Systeemupdate beschikbaar',
		'Last Update Check': 'Laatste updatecheck',
		'Total Users': 'Totaal aantal gebruikers',
		'Total Files': 'Totaal aantal bestanden',
		'Total Storages': 'Totaal aantal opslaglocaties',
		'Appdata Files': 'Appdata bestanden',
		'Total Shares': 'Totaal aantal delen',
		'Link Shares': 'Link delen',
		'Talk Rooms': 'Talkrooms',
		'Federated Sent': 'Federated verzonden',
		'Webserver Type': 'Type webserver',
		'PHP Version': 'PHP versie',
		'PHP Memory Limit': 'PHP geheugenlimiet',
		'Max Upload Size': 'Max upload grootte',
		'Opcache Hit Rate': 'Opcache hit rate',
		'Opcache RAM used': 'Opcache RAM gebruikt',
		'DB Type': 'DB type',
		'DB Version': 'DB versie',
		'DB Size': 'DB grootte',
		'FPM Active Processes': 'FPM actieve processen',
		'FPM Total Processes': 'FPM totale processen',
		'FPM Idle Processes': 'FPM inactieve processen',
		'FPM Accepted Conn': 'FPM geaccepteerde verbindingen',
		'FPM Max Active': 'FPM max actieve processen',
		'APCu Entries': 'APCu entries',
		'APCu Cache Size': 'APCu cache grootte',
		'APCu Hits': 'APCu hits',
		'Active Users (5 min)': 'Actieve gebruikers (5 min)',
		'Active Users (1 h)': 'Actieve gebruikers (1 uur)',
		'Active Users (24 h)': 'Actieve gebruikers (24 uur)',
		'Active Users (1 month)': 'Actieve gebruikers (1 maand)',
	},
	ru: {
		'CPU Load 1min': 'Загрузка CPU 1min',
		'CPU Load 5min': 'Загрузка CPU 5min',
		'CPU Load 15min': 'Загрузка CPU 15min',
		'CPU Cores': 'Ядра CPU',
		'RAM Total': 'Общая память',
		'RAM Free': 'Свободная память',
		'Swap Total': 'Общий Swap',
		'Free Disk Space': 'Свободное место на диске',
		'Memcache Local': 'Memcache локальный',
		'Memcache Locking': 'Memcache блокировка',
		'Installed Apps': 'Установленные приложения',
		'Updates available': 'Доступные обновления',
		'System Update available': 'Доступно обновление системы',
		'Last Update Check': 'Последняя проверка обновлений',
		'Total Users': 'Общее количество пользователей',
		'Total Files': 'Общее количество файлов',
		'Total Storages': 'Общее количество хранилищ',
		'Appdata Files': 'Файлы Appdata',
		'Total Shares': 'Общее количество обменов',
		'Link Shares': 'Ссылочные обмены',
		'Talk Rooms': 'Talk Rooms',
		'Federated Sent': 'Federated отправлено',
		'Webserver Type': 'Тип веб-сервера',
		'PHP Version': 'Версия PHP',
		'PHP Memory Limit': 'Лимит памяти PHP',
		'Max Upload Size': 'Максимальная загрузка',
		'Opcache Hit Rate': 'Opcache hit rate',
		'Opcache RAM used': 'Opcache RAM используется',
		'DB Type': 'Тип БД',
		'DB Version': 'Версия БД',
		'DB Size': 'Размер БД',
		'FPM Active Processes': 'FPM активные процессы',
		'FPM Total Processes': 'FPM общее количество процессов',
		'FPM Idle Processes': 'FPM пустые процессы',
		'FPM Accepted Conn': 'FPM принятые соединения',
		'FPM Max Active': 'FPM максимальное количество активных процессов',
		'APCu Entries': 'APCu записи',
		'APCu Cache Size': 'APCu размер кэша',
		'APCu Hits': 'APCu hits',
		'Active Users (5 min)': 'Активные пользователи (5 мин)',
		'Active Users (1 h)': 'Активные пользователи (1 час)',
		'Active Users (24 h)': 'Активные пользователи (24 часа)',
		'Active Users (1 month)': 'Активные пользователи (1 месяц)',
	},
	uk: {
		'CPU Load 1min': 'Загрузка CPU 1min',
		'CPU Load 5min': 'Загрузка CPU 5min',
		'CPU Load 15min': 'Загрузка CPU 15min',
		'CPU Cores': 'Ядра CPU',
		'RAM Total': 'Общая память',
		'RAM Free': 'Свободная память',
		'Swap Total': 'Общий Swap',
		'Free Disk Space': 'Свободное место на диске',
		'Memcache Local': 'Memcache локальный',
		'Memcache Locking': 'Memcache блокировка',
		'Installed Apps': 'Установленные приложения',
		'Updates available': 'Доступные обновления',
		'System Update available': 'Доступно обновление системы',
		'Last Update Check': 'Последняя проверка обновлений',
		'Total Users': 'Общее количество пользователей',
		'Total Files': 'Общее количество файлов',
		'Total Storages': 'Общее количество хранилищ',
		'Appdata Files': 'Файлы Appdata',
		'Total Shares': 'Общее количество обменов',
		'Link Shares': 'Ссылочные обмены',
		'Talk Rooms': 'Talk Rooms',
		'Federated Sent': 'Federated отправлено',
		'Webserver Type': 'Тип веб-сервера',
		'PHP Version': 'Версия PHP',
		'PHP Memory Limit': 'Лимит памяти PHP',
		'Max Upload Size': 'Максимальная загрузка',
		'Opcache Hit Rate': 'Opcache hit rate',
		'Opcache RAM used': 'Opcache RAM используется',
		'DB Type': 'Тип БД',
		'DB Version': 'Версия БД',
		'DB Size': 'Размер БД',
		'FPM Active Processes': 'FPM активные процессы',
		'FPM Total Processes': 'FPM общее количество процессов',
		'FPM Idle Processes': 'FPM пустые процессы',
		'FPM Accepted Conn': 'FPM принятые соединения',
		'FPM Max Active': 'FPM максимальное количество активных процессов',
		'APCu Entries': 'APCu записи',
		'APCu Cache Size': 'APCu размер кэша',
		'APCu Hits': 'APCu hits',
		'Active Users (5 min)': 'Активные пользователи (5 мин)',
		'Active Users (1 h)': 'Активные пользователи (1 час)',
		'Active Users (24 h)': 'Активные пользователи (24 часа)',
		'Active Users (1 month)': 'Активные пользователи (1 месяц)',
	},
	zh: {
		'CPU Load 1min': 'CPU负载 1min',
		'CPU Load 5min': 'CPU负载 5min',
		'CPU Load 15min': 'CPU负载 15min',
		'CPU Cores': 'CPU核心数',
		'RAM Total': '总内存',
		'RAM Free': '可用内存',
		'Swap Total': '总交换空间',
		'Free Disk Space': '可用磁盘空间',
		'Memcache Local': 'Memcache本地',
		'Memcache Locking': 'Memcache锁定',
		'Installed Apps': '已安装的应用',
		'Updates available': '可用更新',
		'System Update available': '可用系统更新',
		'Last Update Check': '上次更新检查',
		'Total Users': '总用户数',
		'Total Files': '总文件数',
		'Total Storages': '总存储数',
		'Appdata Files': 'Appdata文件',
		'Total Shares': '总共享数',
		'Link Shares': '链接共享',
		'Talk Rooms': 'Talk Rooms',
		'Federated Sent': 'Federated发送',
		'Webserver Type': 'Webserver类型',
		'PHP Version': 'PHP版本',
		'PHP Memory Limit': 'PHP内存限制',
		'Max Upload Size': '最大上传大小',
		'Opcache Hit Rate': 'Opcache命中率',
		'Opcache RAM used': 'Opcache RAM使用',
		'DB Type': 'DB类型',
		'DB Version': 'DB版本',
		'DB Size': 'DB大小',
		'FPM Active Processes': 'FPM活动进程',
		'FPM Total Processes': 'FPM总进程数',
		'FPM Idle Processes': 'FPM空闲进程',
		'FPM Accepted Conn': 'FPM接受连接',
		'FPM Max Active': 'FPM最大活动进程',
		'APCu Entries': 'APCu条目',
		'APCu Cache Size': 'APCu缓存大小',
		'APCu Hits': 'APCu命中',
		'Active Users (5 min)': '活跃用户(5分钟)',
		'Active Users (1 h)': '活跃用户(1小时)',
		'Active Users (24 h)': '活跃用户(24小时)',
		'Active Users (1 month)': '活跃用户(1月)',
	},
	pl: {
		'CPU Load 1min': 'Ładunek CPU 1min',
		'CPU Load 5min': 'Ładunek CPU 5min',
		'CPU Load 15min': 'Ładunek CPU 15min',
		'CPU Cores': 'Liczba rdzeni',
		'RAM Total': 'RAM całkowity',
		'RAM Free': 'RAM wolny',
		'Swap Total': 'Swap całkowity',
		'Free Disk Space': 'Dysk wolny',
		'Memcache Local': 'Memcache lokalny',
		'Memcache Locking': 'Memcache zablokowanie',
		'Installed Apps': 'Zainstalowane aplikacje',
		'Updates available': 'Dostepne aktualizacje',
		'System Update available': 'Dostepne aktualizacje systemowe',
		'Last Update Check': 'Ostatnia sprawdzenie aktualizacji',
		'Total Users': 'Łącznie użytkowników',
		'Total Files': 'Łącznie plików',
		'Total Storages': 'Łącznie magazynów',
		'Appdata Files': 'Pliki Appdata',
		'Total Shares': 'Łącznie udostępnień',
		'Link Shares': 'Linki udostępnień',
		'Talk Rooms': 'Pokoje rozmowy',
		'Federated Sent': 'Wysłane federowane',
		'Webserver Type': 'Typ serwera WWW',
		'PHP Version': 'Wersja PHP',
		'PHP Memory Limit': 'Limit pamięci PHP',
		'Max Upload Size': 'Maksymalny rozmiar pliku',
		'Opcache Hit Rate': 'Opcache Hit Rate',
		'Opcache RAM used': 'Opcache RAM used',
		'DB Type': 'Typ bazy danych',
		'DB Version': 'Wersja bazy danych',
		'DB Size': 'Rozmiar bazy danych',
		'FPM Active Processes': 'Procesy aktywnych FPM',
		'FPM Total Processes': 'Łącznie procesy FPM',
		'FPM Idle Processes': 'Procesy FPM bezczynne',
		'FPM Accepted Conn': 'Zaakceptowane połączenia FPM',
		'FPM Max Active': 'Maksymalne aktywne połączenia FPM',
		'APCu Entries': 'Wpisy APCu',
		'APCu Cache Size': 'Rozmiar pamięci podręcznej APCu',
		'APCu Hits': 'APCu Hits',
		'Active Users (5 min)': 'Aktywni użytkownicy (5 minut)',
		'Active Users (1 h)': 'Aktywni użytkownicy (1 godzina)',
		'Active Users (24 h)': 'Aktywni użytkownicy (24 godziny)',
		'Active Users (1 month)': 'Aktywni użytkownicy (1 miesiąc)',
	},
	pt: {
		'CPU Load 1min': 'Carga do CPU 1min',
		'CPU Load 5min': 'Carga do CPU 5min',
		'CPU Load 15min': 'Carga do CPU 15min',
		'CPU Cores': 'Nucleos',
		'RAM Total': 'RAM Total',
		'RAM Free': 'RAM Livre',
		'Swap Total': 'Swap Total',
		'Free Disk Space': 'Espaco Livre',
		'Memcache Local': 'Memcache Local',
		'Memcache Locking': 'Memcache Locking',
		'Installed Apps': 'Aplicativos Instalados',
		'Updates available': 'Atualizacoes Disponiveis',
		'System Update available': 'Atualizacoes do Sistema Disponiveis',
		'Last Update Check': 'Ultima Verificacao de Atualizacoes',
		'Total Users': 'Total de Usuarios',
		'Total Files': 'Total de Arquivos',
		'Total Storages': 'Total de Armazenamentos',
		'Appdata Files': 'Arquivos de Appdata',
		'Total Shares': 'Total de Compartilhamentos',
		'Link Shares': 'Compartilhamentos por Link',
		'Talk Rooms': 'Salas de Conversa',
		'Federated Sent': 'Enviados Federados',
		'Webserver Type': 'Tipo de Servidor Web',
		'PHP Version': 'Versao do PHP',
		'PHP Memory Limit': 'Limite de Memoria do PHP',
		'Max Upload Size': 'Tamanho Maximo de Upload',
		'Opcache Hit Rate': 'Opcache Hit Rate',
		'Opcache RAM used': 'Opcache RAM used',
		'DB Type': 'Tipo de Banco de Dados',
		'DB Version': 'Versao do Banco de Dados',
		'DB Size': 'Tamanho do Banco de Dados',
		'FPM Active Processes': 'Processos Ativos FPM',
		'FPM Total Processes': 'Total de Processos FPM',
		'FPM Idle Processes': 'Processos FPM Inativos',
		'FPM Accepted Conn': 'Conexoes Aceitas FPM',
		'FPM Max Active': 'Maximo de Conexoes Ativas FPM',
		'APCu Entries': 'Entradas APCu',
		'APCu Cache Size': 'Tamanho da Memoria Cache APCu',
		'APCu Hits': 'APCu Hits',
		'Active Users (5 min)': 'Usuarios Ativos (5 Minutos)',
		'Active Users (1 h)': 'Usuarios Ativos (1 Hora)',
		'Active Users (24 h)': 'Usuarios Ativos (24 Horas)',
		'Active Users (1 month)': 'Usuarios Ativos (1 Mes)',
	},
};

/**
 * Wandelt die strukturierte Liste in das von ioBroker benötigte Format um.
 *
 * @returns Ein Objekt mit Keys und deren Übersetzungen {Key: {de: '...', en: '...'}}.
 */
function getTranslations(): { [key: string]: ioBroker.StringOrTranslated } {
	const result: { [key: string]: any } = {};
	for (const lang in rawTranslations) {
		for (const key in rawTranslations[lang]) {
			if (!result[key]) {
				result[key] = {};
			}
			result[key][lang] = rawTranslations[lang][key];
		}
	}
	return result;
}

export const words = getTranslations();
